### ISSUE TITLE
Problem with requesting url

### ISSUE THREAD

**Issue by ThuGie** [tomysshadow/LeechProtectionRemovalHelp-Xtra#1]
Hi,

If i set to load a dcr from local or webpage it loads it fine,
But once the dcr/cct requests another external with a #SESSIONID
It sends it together with the GET something that should not happen, 
Ending in the webserver not knowing what to do with it.
Normal loading thru webbrowser does not cause this.

Not sure if this is possible to fix but i hope it is.

**Comment by tomysshadow** [comment]
I'm having difficulty understanding what you're describing - does this issue only occur with this Xtra loaded, or is it a general Director problem?

Also - are you loading these files via Lingo, or are they linked?

Also, adding onto this, which Director version are you using?

**Comment by ThuGie** [comment]
pNetVal = getNetText(pDomain & "/b/getservers#JSESSIONID=" & pSessionID & "?" & random(10000))

The code of the game i dont have complete source, has this.
When i use the existing .dcr on website a normal applet load it loads fine just does a /b/getservers 
Once i use your Xtra it sends /b/getservers#SESSIONID=data?3424
causing issues cause a webserver can't handle # at all, its suppose to be client-side.

So not sure if its a problem in director or the Xtra.
But i assume if it loads normally thru applet, it should be possible to load it normally as .exe

**Comment by tomysshadow** [comment]
I'm not understanding given the line of code you posted why it would ever not send the session ID. There could be a few different scenarios happening here. The first is that it's a bug with the INetURL Xtra which doesn't occur in the browser because the browser is used to fetch the URL. The second is that it is calling getNetText elsewhere with a different URL when online. I can see either being pretty much equally likely. I reiterate, which Director version are you using? 8.5.1, 10.1, 11.5.9, 12??

So you have some source code but not all? Did you use ProjectorRays or something? Is it possible I can have a sample to look at it myself?

In any case you could try using setTheRunMode("Plugin") and see if that immediately fixes your issue, as it most likely would if the game is in fact doing something different online.

**Comment by ThuGie** [comment]
Well its split in multiple dcr's this was just from the serverlist dcr, i should have a semi-working source of that i can probably upload, if i recall its 8.5.? that i am using, And yes a version of projectorrays kinda has been used.
The file could also be obtained from http://spineworld.nl/dcr/servers.dcr - original.
So you can just load it as is, on the website with a packet scan what it does the game server should be running although not quite needed i guess.
Trying to make it so, register is done by website and play with pc,  same for login on website, passing a token from website to exe commandline, hoping that works :p.
But got stuck with the # problem.

**Comment by tomysshadow** [comment]
In my experience, network stuff is pretty buggy in 8.5 - any reason you can't use 10.1? You can get a Projector for it here.
https://mega.nz/#F!10oyzSrL!AttpEr-nBc_7GhFy5zQkvA

Is the session ID actually necessary for it to work? Because knowing you used some form or other of ProjectorRays you must have this now as an unprotected file right? Could you potentially edit out the part where it concatenates that to the string altogether?

**Comment by ThuGie** [comment]
Hi,

This is a bit of a bad time for me to actually post this as i don't have much time right now to work on it.
But 1. the projector isnt able to set externalparams.
2. I am not able to successfully decompile all files like the main game file the decompiling isnt 100% successfull. And so i am not able to recreate the files.
Only files i did remake where the loader and the serverlist file
Just stripping the #etc would work for the server file but the main game also uses it to request some data like avatar information.

Unless you know a better decompiler or have a tool that is able to just edit the script remove/edit i don't know of a method to do this, perhaps i could just open it up in hex and see as they are strings and change # to a & sign but for that i would have to check.

**Comment by tomysshadow** [comment]
Yes this is what I mean. Strings in Lingo are just plaintext C Strings, they can be edited in a hex editor fine. There is no direct script editor unfortunately.

**Comment by tomysshadow** [comment]
I am closing this issue as it is not a problem with the Xtra, and therefore something that I can't fix.
